#!/bin/sh

#
# do-backup_rhel5_cis-v1.1.1.sh
##########################################################################
# AUTHOR: Jack Maynard                                                   #
# Created: May 10, 2010 - version 1.0                                    #
#                                                                        #
# RedHat Enterprise Linux 5 (RHEL5)  Security Hardening BACKUP Script    #
# Scripted to Center for Internet Security (CIS) RHEL5 Benchmark v1.1.1  #
# www.cisecurity.org                                                     #
##########################################################################

# Variable Declarations

    NODE=`uname -n`
    TIMESTAMP="`date '+%Y%m%d_%H%M%S'`"
    BACK_DIR="/opt/hp/security/harden/backup/${TIMESTAMP}"

# Make sure the current backup dir exists

    mkdir -p ${BACK_DIR}
    chown root:root ${BACK_DIR}
    chmod 700 ${BACK_DIR}

# Start backup

    clear
    echo ""
    echo "Backup started: `date`"

# Create dynamic revert script

    REVERT="do-revert_rhel5_cis-v1.1.1.sh"

    echo ""
    echo "  * Creating ${REVERT} script"

#################################
#  START CREATE REVERT SCRIPT   #
#################################

cat <<END_SCRIPT > ${BACK_DIR}/${REVERT}
#!/bin/sh

#
##########################################################################
# AUTHOR: HP Consulting - Security & Risk Management, Jack Maynard       #
# Created: May 10, 2010 - HP version 1.0                                 #
#                                                                        #
# RedHat Enterprise Linux 5 (RHEL5)  Security Hardening REVERT Script    #
# This script reverts config files changed by the HP Security hardening  #
# scripts.  It is auto-generated by the "do-backup_rhel5_cis-v1.1.1.sh"  #
# Scripted to Center for Internet Security (CIS) RHEL5 Benchmark v1.1.1  #
# www.cisecurity.org                                                     #
##########################################################################

# Errors for unalias get sent to the console when not 'set'

    unalias rm mv cp 2> /dev/null

    clear
    echo ""
    echo "  Restoring files ..."
    echo ""

    /usr/bin/chattr -i /etc/fstab /boot/grub/menu.lst /boot/grub/grub.conf

    sed -n "94,9999p" ./${REVERT} | while read LINE; 
    
    do
        FILE=\`echo \${LINE} | awk '{print \$1}'\`
        PERMS=\`echo \${LINE} | awk '{print \$2}'\`
        echo "  Restoring \${FILE} with \${PERMS} permissions"
    
        if [ -f .\${FILE} ]; 
        
        then
            /bin/cp -pf .\${FILE} \${FILE}
            /bin/chmod \${PERMS} \${FILE}
        fi
    
    done

    echo ""
    echo "  Completed file restoration."
    echo ""
    echo "  Restoring directories ..."
    echo ""

    for LINE in               \
        /etc/cron.*           \
        /etc/gdm/PreSession   \
        /etc/pam.d            \
        /etc/rc.d             \
        /etc/skel             \
        /etc/xinetd.d         \
        /etc/X11              \
        /root                 \
        /var/spool/cron;
    
    do

        if [ -d .\${LINE} ]; 
        
        then
            echo "  Restoring \${LINE}"        
            /bin/rm -rf \${LINE}
            /bin/cp -pR .\${LINE} \${LINE}
        fi 
        
    done
    
    echo ""
    echo "  Completed directory restoration."
    echo ""
    echo "  Restoring permissions ..."
    echo ""

    
# Restore default permissions for various directories and files
    
    sed -n "1,9999p" ./default-perms | while read LINE; do
    
        FILE=\`echo \${LINE} | awk '{print \$2}'\`
        PERMS=\`echo \${LINE} | awk '{print \$1}'\`
        
        if [ -e \${FILE} ]; then    
        
            echo   "  Restoring \${FILE} permissions to \${PERMS}"
            chmod \${PERMS} \${FILE} 
        fi
        
    done

    echo ""
    echo "  Completed permissions restoration."
    echo ""
    echo "Pre-hardened system configuration restored."
    echo ""

exit 0

### END OF SCRIPT. DYNAMIC DATA FOLLOWS. ###

END_SCRIPT

    chown root:root ${BACK_DIR}/${REVERT}
    chmod 0700 ${BACK_DIR}/${REVERT}

    echo ""
    echo "  * Backing up system configuration files ..."

    # Files that don't natively exist in a virgin RHEL5 system:
    # /etc/at.allow
    # /etc/audit.rules
    # /etc/auditd.conf
    # /etc/cron.allow
    # /etc/ftpaccess
    # /etc/ftpusers
    # /etc/vsftpd.conf
    # /etc/vsftpd.ftpusers
    # /etc/vsftpd/vsftpd.conf
    # /etc/X11/xdm/Xservers
    # /etc/X11/gdm/gdm.conf
    # /etc/X11/gdm/PreSession/Default
    # /etc/X11/xinit/xserverrc
    # /etc/X11/xdm/Xresources
    # /etc/X11/xdm/kdmrc
    # /etc/xinetd.conf
    # /var/spool/cron

    for FILE in \
    /boot/grub/grub.conf \
    /etc/X11/gdm/PreSession/Default \
    /etc/X11/gdm/gdm.conf \
    /etc/X11/xdm/Xresources \
    /etc/X11/xdm/Xservers \
    /etc/X11/xdm/kdmrc \
    /etc/X11/xinit/xserverrc \
    /etc/aliases \
    /etc/at.allow \
    /etc/at.deny \
    /etc/audit.rules \
    /etc/audit/audit.rules \
    /etc/audit/auditd.conf \
    /etc/auditd.conf \
    /etc/bashrc \
    /etc/cron.allow \
    /etc/cron.deny \
    /etc/crontab \
    /etc/csh.cshrc \
    /etc/csh.login \
    /etc/cups/cupsd.conf \
    /etc/exports \
    /etc/fstab \
    /etc/ftpaccess \
    /etc/ftpusers \
    /etc/group \
    /etc/gshadow \
    /etc/hosts.allow \
    /etc/hosts.deny \
    /etc/init.d/functions \
    /etc/init.d/syslog \
    /etc/inittab \
    /etc/issue \
    /etc/issue.net \
    /etc/lilo.conf \
    /etc/login.defs \
    /etc/mail/sendmail.cf \
    /etc/motd \
    /etc/pam.d/su \
    /etc/pam.d/system-auth \
    /etc/passwd \
    /etc/profile \
    /etc/proftpd.conf \
    /etc/securetty \
    /etc/security/access.conf \
    /etc/security/console.perms \
    /etc/security/console.perms.d/50-default.perms \
    /etc/security/limits.conf \
    /etc/shadow \
    /etc/skel/.bashrc \
    /etc/ssh/ssh_config \
    /etc/ssh/sshd_config \
    /etc/sudoers \
    /etc/sysconfig/sendmail \
    /etc/sysctl.conf \
    /etc/syslog.conf \
    /etc/vsftpd.conf \
    /etc/vsftpd.ftpusers \
    /etc/vsftpd/vsftpd.conf \
    /etc/xinetd.conf \
    /root/.bash_profile \
    /root/.bashrc \
    /root/.cshrc \
    /root/.tcshrc \
    /usr/share/config/kdm/Xservers \
    /var/spool/cron;

    do    
        if [ -f $FILE ]; then

            # Backup files that exist (some might not)  

            # Add it to the savelog
            echo "Protected: `ls -lad ${FILE}`" >> ${BACK_DIR}/${REVERT}.savelog
		            
            # Add it to the revert script	    
            echo ${FILE} `find ${FILE} -printf "%m"` >> ${BACK_DIR}/${REVERT}           
        
            DIR=`dirname $FILE`
            [ ! -d $BACK_DIR/$DIR ] && mkdir -p ${BACK_DIR}/${DIR}

                if 
                    [ -L $FILE ]; then         
                        cat ${FILE} > ${BACK_DIR}/${FILE}            
                else
                        cp -pf ${FILE} ${BACK_DIR}/${FILE}
                fi
        else
	    echo "FILE didn't exist on this system (${FILE})." >> ${BACK_DIR}/${REVERT}.savelog
        fi
    done

# Do a backup of .netrc, .rhosts, and .shosts
# in case they are removed by 9.8 script item.

    cat /etc/passwd | cut -d ":" -f6 | sort -u | while read USER
        do
            for FILE in "${USER}/.netrc" "${USER}/.rhosts" "${USER}/.shosts"
            
            do
                if [ -f $FILE ]; then
                
                # Add it to the savelog
                echo "Protected: `ls -lad ${FILE}`" >> ${BACK_DIR}/${REVERT}.savelog
		            
                # Add it to the revert script	    
                echo ${FILE} `find ${FILE} -printf "%m"` >> ${BACK_DIR}/${REVERT}           
        
                DIR=`dirname $FILE`
                [ ! -d $BACK_DIR/$DIR ] && mkdir -p ${BACK_DIR}/${DIR}
     
                cp -pf ${FILE} ${BACK_DIR}/${FILE}
            
                fi    
            done
        done
        
    echo "    Completed file backups."
    echo ""
    echo "  * Backing up permissions ..."

    for DIR in            \
    /etc/cron.*           \
    /etc/gdm/PreSession   \
    /etc/pam.d            \
    /etc/rc.d             \
    /etc/skel             \
    /etc/xinetd.d         \
    /etc/X11              \
    /root                 \
    /var/spool/cron;

    do
        if [ -d $DIR ]; then

            # Add it to the savelog
            echo "Protected: `ls -lad ${DIR}`" >> ${BACK_DIR}/${REVERT}.savelog
	           
            [ ! -d \${BACK_DIR}\${DIR} ] && mkdir -p ${BACK_DIR}${DIR}

            cp -pR ${DIR} ${BACK_DIR}`dirname ${DIR}`
        else 
	    echo "DIR didn't exist on this system (${DIR})." >> ${BACK_DIR}/${REVERT}.savelog
        fi
    done
    
# Backup default permissions for various directories and files.
    
    for ITEM in              \
    /tmp/*                   \
    /usr/local/share/doc     \
    /usr/local/share/man     \
    /usr/share/doc           \
    /usr/share/man           \
    /var/log/*; do

        if [ -e $ITEM ]; then
    
            stat -c "%a %n" $ITEM >> ${BACK_DIR}/default-perms 2>&1
        fi
    
    done
    
# Backup default perms on world-writable directories whose sticky-bit is not set.

    for PART in `awk '($3 ~ "ext2|ext3") { print $2 }' /etc/fstab`; do
    
        find $PART -xdev -type d \( -perm -0002 -a ! -perm -1000 \) \
        | while read ITEM; do 
        
            stat -c "%a %n" $ITEM | sort >> ${BACK_DIR}/default-perms 
            
            done 
            
        done
    
    echo "    Completed permission backups."
    echo ""
    echo "  * Backing up directories ..."


    echo "    Completed directory backups."
    echo ""

    echo "Backup protections are complete: `date`"
    echo ""
    echo "Backup and revert script can be found at:"
    echo ""
    echo "  -----> ../backup/`basename $BACK_DIR`"
    echo ""

# END
